/* eslint-disable @next/next/no-img-element */
/* eslint-disable react/no-unescaped-entities */
import axios from "axios";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRef } from "react";
import ArrowUpIcon from "../components/reusables/icons/arrowUp";
import DownloadIcon from "../components/reusables/icons/download";
import EmailIcon from "../components/reusables/icons/email";
import LinkIcon from "../components/reusables/icons/link";
import LocationIcon from "../components/reusables/icons/location";
import PhoneIcon from "../components/reusables/icons/phone";
import SMSIcon from "../components/reusables/icons/sms";
import TextIcon from "../components/reusables/icons/text";
import UploadIcon from "../components/reusables/icons/upload";
import VCardIcon from "../components/reusables/icons/vcard";
import WifiIcon from "../components/reusables/icons/wifi";

export default function Home() {
  const inputRef = useRef(null);
  const imageRef = useRef(null);
  const handleSubmit = async (event) => {
    event.preventDefault();
    const result = await axios.get(
      `https://api.scanova.io/v2/qrcode/url?url=${inputRef.current.value}&size=m&error_correction=M&data_pattern=RECT&eye_pattern=RECT_RECT&data_gradient_style=None&data_gradient_start_color=%23000000&data_gradient_end_color=%23000000&eye_color_inner=%23000000&eye_color_outer=%23000000&background_color=%23FFFFFF&logo.size=15&logo.excavated=true&logo.angle=0&poster.left=50&poster.top=50&poster.size=40&poster.eyeshape=ROUND_RECT&poster.dataPattern=ROUND&format=svg&apikey=${process.env.NEXT_PUBLIC_API_KEY}`
    );

    imageRef.current.innerHTML = result.data;
  };

  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="left">
        <Link href="/" className="logo">
          <img src="/logo.svg" alt="Logo" />
        </Link>
        <div className="navLinks">
          <button className="link">
            <LinkIcon />
          </button>
          <button className="link">
            <TextIcon />
          </button>
          <button className="link">
            <VCardIcon />
          </button>
          <button className="link">
            <WifiIcon />
          </button>
          <button className="link">
            <LocationIcon />
          </button>
          <button className="link">
            <PhoneIcon />
          </button>
          <button className="link">
            <EmailIcon />
          </button>
          <button className="link">
            <SMSIcon />
          </button>
        </div>
      </div>
      <form className="center" onSubmit={handleSubmit}>
        <div className="textarea">
          <input type="text" placeholder="Enter your text" ref={inputRef} />
          <p>Your QR code will be generated automatically on 'enter'</p>
        </div>
        <label htmlFor="fileInput">
          <input type="file" id="fileInput" />
          <button
            type="button"
            onClick={() => document.getElementById("fileInput").click()}
          >
            <div className="icon">
              <UploadIcon />
            </div>
            <div className="text">
              <span>Upload any file</span> (.jpg, .pdf, .mp3, .docx, .pptx)
            </div>
          </button>
        </label>
      </form>
      <div className="right">
        <div className="qrImage" ref={imageRef}>
          <img src="/qrcode.png" alt="qr code" />
        </div>
        <div className="controls">
          <div className="toggler">
            <button>
              <div className="text">Frame</div>
              <div className="arrow">
                <ArrowUpIcon />
              </div>
            </button>
            <div className="dropdown">
              <button>
                <img src="/qrcode.png" alt="qr code" />
              </button>
              <button>
                <img src="/qrcode.png" alt="qr code" />
              </button>
              <button>
                <img src="/qrcode.png" alt="qr code" />
              </button>
              <button>
                <img src="/qrcode.png" alt="qr code" />
              </button>
              <button>
                <img src="/qrcode.png" alt="qr code" />
              </button>
            </div>
          </div>
          <div className="toggler">
            <button>
              <div className="text">Frame</div>
              <div className="arrow">
                <ArrowUpIcon />
              </div>
            </button>
            <div className="dropdown">
              <button>
                <img src="/qrcode.png" alt="qr code" />
              </button>
              <button>
                <img src="/qrcode.png" alt="qr code" />
              </button>
              <button>
                <img src="/qrcode.png" alt="qr code" />
              </button>
              <button>
                <img src="/qrcode.png" alt="qr code" />
              </button>
              <button>
                <img src="/qrcode.png" alt="qr code" />
              </button>
            </div>
          </div>
          <div className="logo"></div>
        </div>
        <div className="buttons">
          <button className="jpg">
            <div className="icon">
              <DownloadIcon />
            </div>
            <div className="text">JPG</div>
          </button>
          <button className="svg">
            <div className="icon">
              <DownloadIcon />
            </div>
            <div className="text">SVG</div>
          </button>
        </div>
      </div>
    </div>
  );
}
